apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-service-config
data:
  MAIL_HOST: "gmail"
  MAIL_USERNAME: "XXXXXXX"
  MAIL_PASSWORD: "XXXXXXX"
  RABBITMQ_USERNAME: "user"
  RABBITMQ_PASSWORD: "ilovepasswords"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service-deployment
  labels:
    app: fillup
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fillup
      tier: backend
  template:
    metadata:
      name: mail-service-pod
      labels:
        app: fillup
        tier: backend
    spec:
      initContainers:
      - name: init-wait-rabbitmq
        image: curlimages/curl:8.10.1
        command:
        - sh
        - -c
        - |
          until curl -s -o /dev/null -w ''%{http_code}'' http://rabbitmq:15672; do
            echo "Waiting for RabbitMQ to start..."
            sleep 5
          sleep 10
          done
      containers:
        - name: mail-service
          image: punnyoz/fillup-mail-service:latest
          ports:
            - containerPort: 25
            - containerPort: 465
            - containerPort: 587
            - containerPort: 2525
          envFrom:
          - configMapRef:
              name: mail-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: fillup
    tier: backend
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: smtp-ssl
      port: 465
      targetPort: 465
    - name: submission
      port: 587
      targetPort: 587
    - name: alternate-smtp
      port: 2525
      targetPort: 2525