apiVersion: v1
kind: ConfigMap
metadata:
  name: water-station-service-config
data:
  PORT: "5000"
  NODE_ENV: "development"
  DB_URL: "mongodb://mongodb:27017/fillup"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: water-station-service-deployment
  labels:
    app: fillup
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fillup
      tier: backend
  template:
    metadata:
      name: water-station-service-pod
      labels:
        app: fillup
        tier: backend
    spec:
      containers:
        - name: water-station-service
          image: punnyoz/fillup-water-station-service:latest
          ports:
            - containerPort: 5000
          envFrom:
          - configMapRef:
              name: water-station-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: water-station-service
spec:
  selector:
    app: fillup
    tier: backend
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
---