apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
  MONGO_INITDB_DATABASE: "fillup"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  init.js: |
    db.createUser({
      user: "fillup",
      pwd: "filluppassword",
      roles: [
        {
          role: "readWrite",
          db: "fillup"
        }
      ]
    });
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0.3
          ports:
            - containerPort: 27017
              name: mongodb
          envFrom:
          - configMapRef:
              name: mongodb-config
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data-pvc
        - name: mongodb-init
          configMap:
            name: mongodb-init
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as necessary
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
---