services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.9'
    # platform: 'linux/arm64'
    container_name: my-rabbitmq
    environment:
      RABBITMQ_ERL_COOKIE: 'securestring'
      RABBITMQ_USERNAME: 'admin'
      RABBITMQ_PASSWORD: 'ilovepasswords'
      RABBITMQ_VHOST: '/'
      RABBITMQ_PLUGINS: "rabbitmq_management"
    ports:
      - '8080:15672'
      - '5672:5672'
